catnap:
  tcp_echo:
    - scenario0:
      bufsize: 64
      nclients: 1
      nrequests: 100000
      run_mode: concurrent
catnip:
  tcp_echo:
    - scenario0:
      bufsize: 64
      nclients: 1
      nrequests: 100000
      run_mode: concurrent
catpowder:
  tcp_echo:
    - scenario0:
      bufsize: 64
      nclients: 1
      nrequests: 100000
      run_mode: concurrent
