# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

all: all-c all-cs

all-c:
	$(MAKE) -C c all

all-cs:
	$(MAKE) -C cs all

clean: clean-c clean-cs

clean-c:
	$(MAKE) -C c clean

clean-cs:
	$(MAKE) -C cs clean
