# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# Builds everything.
all:
	dotnet build --configuration Release

# Cleans up build artifacts.
clean:
	dotnet clean
	rm -rf bin obj
