# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Catnap (Linux Kernel)

concurrency:
  group: catnap
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - unstable
      - dev

env:
  LIBOS: catnap
  SERVER: ${{ secrets.CATNAP_HOSTNAME_A }}
  CLIENT: ${{ secrets.CATNAP_HOSTNAME_B }}
  SERVER_ADDR: 10.3.1.10
  CLIENT_ADDR: 10.3.1.11
  SHOULD_RUN_RELEASE: ${{ github.ref_name == 'main' || github.ref_name == 'unstable' || github.ref_name == 'dev' || contains(github.head_ref, 'do-release') }}

jobs:

  debug-pipeline:
    name: Catnap Debug Pipeline (Linux Kernel)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p $HOME/.ssh/
        echo "${{ secrets.SSHKEY }}" > "$HOME/.ssh/id_rsa"
        chmod 400 $HOME/.ssh/id_rsa
        echo "Host *" > $HOME/.ssh/config
        echo -e "\tStrictHostKeyChecking no" >> $HOME/.ssh/config
        echo -e "\tIdentityFile $HOME/.ssh/id_rsa" >> $HOME/.ssh/config
        echo -e "\tIdentitiesOnly yes" >> $HOME/.ssh/config
        echo -e "\tPasswordAuthentication no" >> $HOME/.ssh/config
        echo -e "\tUser ${{ secrets.USERNAME }}" >> $HOME/.ssh/config
        echo -e "\tPort ${{ secrets.PORTNUM }}" >> $HOME/.ssh/config
    - name: Run
      run: |
        branch_name=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
        python3 -u tools/demikernel_ci.py \
          --platform linux \
          --server $SERVER \
          --client $CLIENT \
          --repository demikernel \
          --branch origin/$branch_name \
          --libos $LIBOS \
          --debug \
          --test-unit --test-integration --test-system all \
          --delay 2 \
          --server-addr $SERVER_ADDR \
          --client-addr $CLIENT_ADDR
    - name: Archive Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: catnap-debug-pipeline-logs
        path: |
          **/*.stdout.txt
          **/*.stderr.txt

  release-pipeline:
    name: Catnap Release Pipeline (Linux Kernel)
    needs: debug-pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Print if release pipeline should not run
      if: ${{ env.SHOULD_RUN_RELEASE == 'false' }}
      run: echo "Release pipeline skipped because branch is not main, unstable, dev, or does not contain 'do-release'."
    - name: Checkout
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup SSH
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      shell: bash
      run: |
        mkdir -p $HOME/.ssh/
        echo "${{ secrets.SSHKEY }}" > "$HOME/.ssh/id_rsa"
        chmod 400 $HOME/.ssh/id_rsa
        echo "Host *" > $HOME/.ssh/config
        echo -e "\tStrictHostKeyChecking no" >> $HOME/.ssh/config
        echo -e "\tIdentityFile $HOME/.ssh/id_rsa" >> $HOME/.ssh/config
        echo -e "\tIdentitiesOnly yes" >> $HOME/.ssh/config
        echo -e "\tPasswordAuthentication no" >> $HOME/.ssh/config
        echo -e "\tUser ${{ secrets.USERNAME }}" >> $HOME/.ssh/config
        echo -e "\tPort ${{ secrets.PORTNUM }}" >> $HOME/.ssh/config
    - name: Run
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      run: |
        branch_name=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
        python3 -u tools/demikernel_ci.py \
          --platform linux \
          --server $SERVER \
          --client $CLIENT \
          --repository demikernel \
          --branch origin/$branch_name \
          --libos $LIBOS \
          --test-unit --test-integration --test-system all \
          --delay 2 \
          --server-addr $SERVER_ADDR \
          --client-addr $CLIENT_ADDR
    - name: Archive Logs
      if: always()
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: catnap-release-pipeline-logs
        path: |
          **/*.stdout.txt
          **/*.stderr.txt

  report-performance:
    name: Catnap Performance Report (Linux Kernel)
    needs: release-pipeline
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
      pull-requests: write
      security-events: write
    steps:
    - name: Print if release pipeline should not run
      if: ${{ env.SHOULD_RUN_RELEASE == 'false' }}
      run: echo "Release pipeline skipped because branch is not main, unstable, dev, or does not contain 'do-release'."
    - name: Checkout
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download Release Pipeline Logs
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: catnap-release-pipeline-logs
        path: ./catnap_release_pipeline_logs
    - name: Setup FlameGraph Repository
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      run: |
        git clone https://github.com/brendangregg/FlameGraph.git /tmp/FlameGraph
    - name: Parse Statistics
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      id: parse-stats
      run: |
        branch_name=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
        pip install pandas tabulate
        stats=$(python3 -u tools/perf.py \
          --branch origin/$branch_name \
          --libos $LIBOS \
          --log-dir ./catnap_release_pipeline_logs)
    - name: Archive Performance Data
      if: ${{ env.SHOULD_RUN_RELEASE == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: performance-data
        path: |
          **/perf_data.csv
          **/flamegraph.svg
